/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class LCAKernel_LCAKernel */

#ifndef _Included_LCAKernel_LCAKernel
#define _Included_LCAKernel_LCAKernel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     LCAKernel_LCAKernel
 * Method:    createdb
 * Signature: (IDLjava/lang/String;Ljava/lang/String;Ljava/lang/String;IIIIILjava/lang/String;JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_LCAKernel_LCAKernel_createdb
  (JNIEnv *, jobject, jint, jdouble, jstring, jstring, jstring, jint, jint, jint, jint, jint, jstring, jlong, jint);

/*
 * Class:     LCAKernel_LCAKernel
 * Method:    deletedb
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_LCAKernel_LCAKernel_deletedb
  (JNIEnv *, jobject, jlong);

/*
 * Class:     LCAKernel_LCAKernel
 * Method:    updatedb
 * Signature: (JIDLjava/lang/String;Ljava/lang/String;Ljava/lang/String;IIIIILjava/lang/String;JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_LCAKernel_LCAKernel_updatedb
  (JNIEnv *, jobject, jlong, jint, jdouble, jstring, jstring, jstring, jint, jint, jint, jint, jint, jstring, jlong, jint);

/*
 * Class:     LCAKernel_LCAKernel
 * Method:    QBAinverse
 * Signature: (IDLjava/lang/String;Ljava/lang/String;Ljava/lang/String;IIIIILjava/lang/String;JIJJ)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_LCAKernel_LCAKernel_QBAinverse
  (JNIEnv *, jobject, jint, jdouble, jstring, jstring, jstring, jint, jint, jint, jint, jint, jstring, jlong, jint, jlong, jlong);

/*
 * Class:     LCAKernel_LCAKernel
 * Method:    libUpstreamLCIA
 * Signature: (IDLjava/lang/String;Ljava/lang/String;Ljava/lang/String;IIIIILjava/lang/String;JIJJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_LCAKernel_LCAKernel_libUpstreamLCIA
  (JNIEnv *, jobject, jint, jdouble, jstring, jstring, jstring, jint, jint, jint, jint, jint, jstring, jlong, jint, jlong, jlong);

/*
 * Class:     LCAKernel_LCAKernel
 * Method:    libUpstreamUncertainty
 * Signature: (IDLjava/lang/String;Ljava/lang/String;Ljava/lang/String;IIIIILjava/lang/String;JIJJ)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_LCAKernel_LCAKernel_libUpstreamUncertainty
  (JNIEnv *, jobject, jint, jdouble, jstring, jstring, jstring, jint, jint, jint, jint, jint, jstring, jlong, jint, jlong, jlong);

/*
 * Class:     LCAKernel_LCAKernel
 * Method:    staticAndstochastic
 * Signature: (IDLjava/lang/String;Ljava/lang/String;Ljava/lang/String;IIIIILjava/lang/String;JIJJI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_LCAKernel_LCAKernel_staticAndstochastic
  (JNIEnv *, jobject, jint, jdouble, jstring, jstring, jstring, jint, jint, jint, jint, jint, jstring, jlong, jint, jlong, jlong, jint);

/*
 * Class:     LCAKernel_LCAKernel
 * Method:    stochastic
 * Signature: (IDLjava/lang/String;Ljava/lang/String;Ljava/lang/String;IIIIILjava/lang/String;JIJJI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_LCAKernel_LCAKernel_stochastic
  (JNIEnv *, jobject, jint, jdouble, jstring, jstring, jstring, jint, jint, jint, jint, jint, jstring, jlong, jint, jlong, jlong, jint);

/*
 * Class:     LCAKernel_LCAKernel
 * Method:    static_calc
 * Signature: (IDLjava/lang/String;Ljava/lang/String;Ljava/lang/String;IIIIILjava/lang/String;JIJJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_LCAKernel_LCAKernel_static_1calc
  (JNIEnv *, jobject, jint, jdouble, jstring, jstring, jstring, jint, jint, jint, jint, jint, jstring, jlong, jint, jlong, jlong);

/*
 * Class:     LCAKernel_LCAKernel
 * Method:    static_basic_calc
 * Signature: (IDLjava/lang/String;Ljava/lang/String;Ljava/lang/String;IIIIILjava/lang/String;JIJJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_LCAKernel_LCAKernel_static_1basic_1calc
  (JNIEnv *, jobject, jint, jdouble, jstring, jstring, jstring, jint, jint, jint, jint, jint, jstring, jlong, jint, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
